# -------------------------------------------------------
# Secret für Postgres-Passwort und Flask DATABASE_URL
# -------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Passwort für Postgres (unbedingt nach dem Apply anpassen!)
  postgres-password: password123
  # DATABASE_URL für Flask (gleiche Credentials)
  database_url: postgresql://appuser:password123@postgres-headless:5432/todos_db
---
# -------------------------------------------------------
# Headless Service für Postgres (StatefulSet)
# -------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  labels:
    app: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
# -------------------------------------------------------
# StatefulSet für Postgres mit Persistent Volume Claim
# -------------------------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: postgres-headless
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "appuser"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres-password
            - name: POSTGRES_DB
              value: "todos_db"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
        labels:
          app: postgres
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
# -------------------------------------------------------
# Deployment für die Flask-Todo-Anwendung
# -------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-example-deployment
  labels:
    app: flask-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-example
  template:
    metadata:
      labels:
        app: flask-example
    spec:
      containers:
        - name: flask-example
          image: flask-example:1.0
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: database_url
---
# -------------------------------------------------------
# Service für die Flask-Todo-API (interner Zugriff im Cluster)
# -------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-example
spec:
  type: ClusterIP
  selector:
    app: flask-example
  ports:
    - port: 5000
      targetPort: 5000