# -------------------------------------------------------
# Secret für Postgres-Passwort und Flask DATABASE_URL
# -------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: flask-todo-secrets
type: Opaque
stringData:
  # Passwort für Postgres (unbedingt nach dem Apply anpassen!)
  postgres-password: securepassword
  # DATABASE_URL für Flask (gleiche Credentials)
  database_url: postgresql://todo_user:securepassword@postgres-headless:5432/todo_db
