name: CI Pipeline

on:
  push:
    branches:
#      - 'major'
      - 'minor'
  pull_request:
    branches:
#      - 'major'
      - 'minor'

jobs:
  build-test-major:
    if: ${{ github.ref_name == 'major' }}
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Code formatieren mit Black
        run: black --check .

      - name: Linting mit Flake8
        run: flake8 .

      - name: Typüberprüfung mit Mypy
        run: mypy .

      - name: Tests ausführen
        run: pytest

      - name: Docker-Image bauen
        run: docker build -t my_project:latest .

      - name: Trivy-Sicherheitsscan
        uses: aquasecurity/trivy-action@v0.9.2
        with:
          image-ref: my_project:latest

  build-test-minor:
    if: ${{ github.ref_name == 'minor' }}
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Code formatieren mit Black
        run: black --line-length=79 .

      - name: Linting mit Flake8
        run: flake8 .

      - name: Typüberprüfung mit Mypy
        run: mypy .

#      - name: Tests ausführen
#        run: pytest
